### PR TITLE
Release17.12

### PR DESCRIPTION
**Pull request by alexbodn**
a handful of bug fixes
explained in each commit
(OFBIZ-11817, OFBIZ-11818)

### CODE REVIEW

**Comment by mbrohl** [comment]
Alex, please do bugfixes in the trunk branch and file a Jira for each bugfix separately, marked with the correct "afftects version" revisions. We do not merge multi-purpose pull requests to the codebase and reviewing is difficult.

See my comment at https://issues.apache.org/jira/browse/OFBIZ-11817 . Thank you.

**Comment by JacquesLeRoux** [comment]
BTW Alex,

If you are interested in contributing this page would help you: https://cwiki.apache.org/confluence/display/OFBIZ/OFBiz+Contributors+Best+Practices

It's a bit heavy, needs update and simplification but may help.

**Comment by JacquesLeRoux** [comment]
Hi Alex,

Not sure why you are still pushing here. You know this will never be merged because we only merge PRs in trunk (our master if you prefer), and then backport from there, right? Of course there are exceptions like what I did at https://issues.apache.org/jira/browse/OFBIZ-11881, but they are extremely rare.

**Comment by mbrohl** [comment]
@alexbodn are you aware that this cannot be handled the way you set it up?
We appreciate your work but it should be targeted against trunk and split into separate commits.

Thank you!

**Comment by mbrohl** [comment]
Closing this pull request due to lack of response from the contributor to fix the issues.

**Pull request closed without merging**
