### PR TITLE
Improved: have profileMenuLocation (OFBIZ-12981)

### PR DESCRIPTION
**Pull request by PierreSmits**
Profile screens are used in various components as portalpageportlets, and have references to various party menus. As menus in the various profile screens are parameterized to use ${parameters.mainMenuLocation} this generates errors in the components/applications where these screens are used as portal page elements. Having a context-param profileMenuLocation resolves this issue.

modified:
myportal-web.xml: have contex-param profileMenuLocation

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Thanks Pierre, the AssetMaint integration tests pass?

**Comment by PierreSmits** [comment]
HI @JacquesLeRoux,

the AssetMaint integration aspect got **accidentally** in this, but is something you committed to the main branch 4 days ago via https://github.com/apache/ofbiz-plugins/commit/21aff950ea312d20df33aebda2dd25053792f797

I apologize if some things got crossed.

**Comment by JacquesLeRoux** [comment]
I meant: did you run `gradlew "ofbiz --test component=assetmain"` ?

**Comment by PierreSmits** [comment]
Hi @JacquesLeRoux 

I did not. As the changes in this are in the web.xml file, which only affect the UI side and not any tests.

However, I just ran the test against the main branch (trunk, up tp date per 07:00 this morning) and it failed. So something before that moment must have gone wrong in FixedAssetMaintTests.groovy

**Comment by PierreSmits** [comment]
Did you run the test(s)?

**Comment by JacquesLeRoux** [comment]
Hi Pierre,

> the changes in this are in the web.xml file, which only affect the UI side and not any tests.

Wrong you also modified FixedAssetMaintTests and it's different than locally. 
To run the tests I'd need to patch locally. I have enough on my plate. So my question remains: 
>did you run gradlew "ofbiz --test component=assetmain" ? (in your branch)

**Comment by JacquesLeRoux** [comment]
With https://issues.apache.org/jira/browse/OFBIZ-12985
we have completly fixed all the integration tests. Why would you want to change
assetmaint/src/main/groovy/org/apache/ofbiz/assetmaint/assetmaint/test/FixedAssetMaintTests.groovy?

**Comment by PierreSmits** [comment]
Closing this. Time for a do-over as it is giving to much headache.

**Pull request closed without merging**
