### PR TITLE
Implemented: have a license

### PR DESCRIPTION
**Pull request by PierreSmits**
(OFBIZ-11451)

### CODE REVIEW

**Comment by jacopoc** [comment]
The LICENSE file is now missing some sections: please double check my code review of PR #8

**Comment by JacquesLeRoux** [comment]
Also why not a NOTICE file like in framework? 

I really don't like to have to repeat the same in GH and Jira :/ One reason more to pick one and only one tool :)

**Comment by jacopoc** [comment]
@JacquesLeRoux the LICENSE files you have committed and backported are incomplete, as I wrote in my code review. Why are you ignoring my remarks and why aren't you reviewing these contribution before merging them?

**Comment by mbrohl** [comment]
Interesting question for me: how would we now reopen this issue to track the pending correction?

**Comment by JacquesLeRoux** [comment]
@jacopoc , Actually I trusted Pierre's work. And as I wrote in the comment above yours and in the https://cwiki.apache.org/confluence/display/OFBIZ/GITHUB+plus+GIT+VS+JIRA+plus+GIT page (we really need to change the title):
> When you use both Jira and GH and cross on wire with a peer you "have to" repeat on the other side to be sure to be understood

we crossed on wire, that's why. I forgot to commit the wiki page, it's now done.

So it was too late. Anyway don't we need to add a NOTICE file too?

**Comment by JacquesLeRoux** [comment]
@mbrohl You can only if it has not been merged (so committed), ie only "Closed by hand". Solution: create a new PR. I don't think it's bad for Git, it follows its philosophy.

**Comment by jacopoc** [comment]
@JacquesLeRoux, @PierreSmits I understand that Jacques trusted Pierre's work without reviewing it and merged the pull request. However Pierre didn't implement the new LICENSE file according to the remarks in my code review #8, so now the LICENSE file that has been contributed is incomplete. Who is going to take care of reading my code review and correcting the file? Do my remarks make sense?

**Comment by JacquesLeRoux** [comment]
Either Pierre or I, the 1st available to do it... BTW you could do it too, like any person committed to be a commiter for the project...

**Comment by JacquesLeRoux** [comment]
And what about the NOTICE file, I guess we need one in plugins too, right?

**Comment by JacquesLeRoux** [comment]
Done with added NOTICE. BTW should we not update the Copyright dates? Currently 2001-2008

**Pull request merged**
