### PR TITLE
OFBIZ-11756 vue js renderer

### PR DESCRIPTION
**Pull request by Olivier-Heintz**
Implemented: add plugins to have ofbiz components usable with the vuejs renderer (OFBIZ-11756)

Explanation
3-4 new addons: vuejs, themefrontjs, examplefjs and partyfjs to be able to have a complete usage of vuejs renderer (included in vuejs plugin)

Thanks: to Julien Bachelier for Vue.Js code in vuejs plugin

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Hi Olivier,

SonarCloud Code Analysis was not good :/ Could you please check?

After that I'll check  all "SonarCloud Quality Gate failed." messages to "apache/ofbiz-*<ofbiz-*@noreply.github.com>" they went unnoticed so far

**Comment by JacquesLeRoux** [comment]
Hi Olivier,

It seems uneasy but please check the issues reported by "SonarCloud Quality Gate ", TIA

**Comment by mbrohl** [comment]
@Olivier-Heintz This PR seems to be problematic in several aspects:
- there is too much code duplication, see sonarcloud analysis. Please try to avoid copied inline functions and write them in separate function to reuse them
- the commits do not follow the commit message template (Fixed:, Improved: etc.)

**Comment by mbrohl** [comment]
If you want to show that this is a draft PR which is not finished yet to be reviewed and merged, you can also specify a "draft pull request". I did not find a way to specify this afterwards so you might need to provide a new PR instead.

**Comment by Olivier-Heintz** [comment]
Thank you Michael for your remarks.
This PR is to show what is working but clearly, not yet ready to be merge.
I will try to create a "draft pull request".

PS: Currently, my knowledge of vuejs is not enough to remove all duplicate lines !

**Pull request closed without merging**
