### PR TITLE
Improved: fix cross-app menu location issues (Ofbiz 13035)

### PR DESCRIPTION
**Pull request by PierreSmits**
address cross application menu-location issues.

modified:
in SCRUM: web.xml - add context-param for profileMenuLocation
in PROJECT: web.xml - add context-param for requestMenuLocation
in MYPORTAL: web.xml - add context-param for profileMenuLocation, added context-param timesheetMenuLocation
- Project/web.xml: added context-param timesheetMenuLocation
- Project/TimeSheetScreens.xml: changed ref and location  regarding timesheet actions
- Scrum/web.xml: added context-param timesheetMenuLocation

### CODE REVIEW

**Comment by PierreSmits** [comment]
@JacquesLeRoux 
This should be the last one in plugins (fingers crossed).

**Comment by JacquesLeRoux** [comment]
@PierreSmits 
Just see my comments at https://issues.apache.org/jira/browse/OFBIZ-13035
I'll try to apply the patch with Git, not possible with Eclipse.

**Comment by JacquesLeRoux** [comment]
@PierreSmits 

C:\projectsASF\Git\ofbiz-framework\plugins>git pull
Already up to date.

C:\projectsASF\Git\ofbiz-framework\plugins>git apply ..\111.patch
error: patch failed: scrum/webapp/scrum/WEB-INF/web.xml:39
error: scrum/webapp/scrum/WEB-INF/web.xml: patch does not apply
error: patch failed: projectmgr/webapp/projectmgr/WEB-INF/web.xml:42
error: projectmgr/webapp/projectmgr/WEB-INF/web.xml: patch does not apply
error: patch failed: myportal/webapp/myportal/WEB-INF/web.xml:53
error: myportal/webapp/myportal/WEB-INF/web.xml: patch does not apply
error: patch failed: projectmgr/webapp/projectmgr/WEB-INF/web.xml:47
error: projectmgr/webapp/projectmgr/WEB-INF/web.xml: patch does not apply
error: patch failed: projectmgr/widget/TimeSheetScreens.xml:231
error: projectmgr/widget/TimeSheetScreens.xml: patch does not apply
error: patch failed: scrum/webapp/scrum/WEB-INF/web.xml:44
error: scrum/webapp/scrum/WEB-INF/web.xml: patch does not apply

**Comment by PierreSmits** [comment]
HI @JacquesLeRoux 

I will look into this. Please do not forget to review/merge related https://github.com/apache/ofbiz-framework/pull/771

**Pull request closed without merging**
