### PR TITLE
Improved: Ecommerce - parameterized menu location (OFBIZ-13042)

### PR DESCRIPTION
**Pull request by PierreSmits**
modified:
- web.xml: added mainMenuLocation
- BlogScreens.xml: changed menuLocation

added:
- EcommerceMenus.xml

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Hi @PierreSmits,

Patching works but getting to blogs. I locally get this error:

> ERROR MESSAGE
> java.lang.RuntimeException: Error rendering included menu named [ViewEdit] at location [${parameters.mainMenuLocation]: java.lang.IllegalArgumentException: Could not find menu file in location [${parameters.mainMenuLocation]
>

**Comment by PierreSmits** [comment]
Hi @JacquesLeRoux ,

Thanks for your due-diligence.

I will look into this

**Comment by PierreSmits** [comment]
HI @JacquesLeRoux,

As there is only one menu in BlogMenu.xml, I will move the menu to the default menu (EcommerceMenus.xml) and remove the BlogMenus.xml file in an update of this pull request.

Then, in a next ticket we could work to move the remaining Blog*.xml files into the main widget folder as there is no need to keep the remaining 4 Blog*.xml files stay in a sub-folder.

**Comment by JacquesLeRoux** [comment]
Hi Pierre,

Test OK, your proposition sounds reasonable to me since only blog*.xml are apart

**Pull request merged**
