### PR TITLE
Improved: project -  simplified uris (OFBIZ-11792)

### PR DESCRIPTION
**Pull request by PierreSmits**
reworked web.xml, widgets and other xml files to have simplified project uris.

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Hi Pierre,

The Sonar Could Code Analysis is no longer available. So I don't know why it reports 3 bugs, even more intriguing w/o any Java files involved. Nevertheless, there is at least one problem with your change. If you start by login in another application you can't jump to project w/o an error. The reason is other applications still refer to project through control/main. So you would need to handle this case apart if you don't want to provide something big like https://issues.apache.org/jira/browse/OFBIZ-11354. I mean another OFBIZ-11791 sub-task with a patch to be applied before all other where all application would refer to each others w/o "control/main". HTH

**Comment by PierreSmits** [comment]
@JacquesLeRoux 

1 year after I would also suspect that some features would not be available.

What do you suggest?

**Comment by JacquesLeRoux** [comment]
Hi Pierre,

As I said this is not a problem. We can always try locally. ALso we know that we should not use SonarCloud Code Analysis in GH but w/ Gradle.

I already suggested to resolve the issue when coming from other applications.

**Comment by PierreSmits** [comment]
Jacques,

Regarding the off-track discussion, it seems to me that you already addressed it (together with INFRA) relating to another issue.

**Comment by PierreSmits** [comment]
Jacques, 

Addressing the other issue with another ticket (and a subsequent pull request/patch file - for those still working with SVN, yay....) while not resolving the existing sub-tickets under OFBIZ-11791 seems to be leading to the same circular, chicken-egg discussion that have been there on other improvement aspects in the past. 

And for some these changes are either too big, too small, too complex or too mediocre to collaborate on (take your pick). All in all, though desired (see user ml), not moving forward.

**Comment by JacquesLeRoux** [comment]
Pierre,

I can't push this, and I guess others related PRs, when it breaks the navigation. Did you try, before creating the PR(s)?

We need to address that 1st. It's not a  chicken-egg issue. If you apply the patch/PR then coming from any other applications fails. 

This comes from themes. Look for <#assign thisURL = thisURL + "/control/main"> in *.ftl files you will see what I mean.

So it should not be a big task to do that before doing all the rest.

**Comment by JacquesLeRoux** [comment]
After few hours trying, won't do

**Pull request closed without merging**
