### PR TITLE
OFBIZ-10954 Have a country dimension

### PR DESCRIPTION
**Pull request by PierreSmits**
This PR contains additions to

1. the entity group
2. the entity model

### CODE REVIEW

**Comment by pwverma** [comment]
I am not having access to merge this PR, Do I need to setup something?

@JacquesLeRoux tagging you here as I saw you merge from github ;)

**Review by pwverma — APPROVED** [review]

**Comment by swapnilmmane** [comment]
> I am not having access to merge this PR, Do I need to setup something?
> 
> @JacquesLeRoux tagging you here as I saw you merge from github ;)

Hi @verma-pawan,
You will need to link you ASF and GitHub account, please refer https://gitbox.apache.org/

**Comment by pwverma** [comment]
> > I am not having access to merge this PR, Do I need to setup something?
> > @JacquesLeRoux tagging you here as I saw you merge from github ;)
> 
> Hi @verma-pawan,
> You will need to link you ASF and GitHub account, please refer https://gitbox.apache.org/

Thanks, Swapnil for the information, I'll setup it soon :)

**Comment by PierreSmits** [comment]
Thanks, @verma-pawan & @swapnilmmane, for your participation and support.

**Comment by JacquesLeRoux** [comment]
Hi @verma-pawan,

Beware that if you merge a PR from GitHub you will not be able to use our commit template, see https://markmail.org/message/nmadztprvucz4mlv for more

Thanks
PS: IMO a good way is to do it as Nicolas did at https://github.com/apache/ofbiz-framework/pull/7#issuecomment-579750158. In other word, he did not merge in GitHub but followe our process where the commit template is used. Maybe this still needs discussion but for now I'd priviledge this way.

**Comment by swapnilmmane** [comment]
+1 to @JacquesLeRoux's comment.

@verma-pawan and team,
I still feel, if possible we should avoid merging PR through GitHub, till we don't conclude the thread mentioned by Jacques (https://markmail.org/message/nmadztprvucz4mlv).

**Comment by pwverma** [comment]
Thanks @JacquesLeRoux @swapnilmmane for the details. I have committed changes(Trunk#ccb6219954a0b523b8ff854da5954af2feaab8d0) of this PR using our pattern. 
I have linked my ASF and GitHub accounts. Still, I am unable to see Merge and Close buttons for this PR. As changes of this PR has been committed this should be close. Thanks!

**Comment by pwverma** [comment]
Got the access now. Thanks!

**Pull request closed without merging**
