### PR TITLE
Improved: convert createProject service (OFBIZ-12983)

### PR DESCRIPTION
**Pull request by PierreSmits**
convert createProject service code from mini-lang to groovy DSL

modified:
- services.xml: changed engine, location and description 
- ProjectServices.xml: removed simple-method

added:
- ProjectServices.groovy: having createProject

### CODE REVIEW

**Comment by mbrohl** [comment]
Please check parameter validation. Parameters should not only be checked for existence but also if the contain empty strings like it was done with if-not-empty checks before.

**Comment by PierreSmits** [comment]
> Please check parameter validation. Parameters should not only be checked for existence but also if the contain empty strings like it was done with if-not-empty checks before.

Thanks Michael
Your suggestion have been incorporated in latest commit.

**Comment by JacquesLeRoux** [comment]
The last changes look good, I guess inpired by previous migration work. I'll do a complete review later

**Comment by JacquesLeRoux** [comment]
BTW Pierre you did not take into account Michael's remark. Note that we should not use UtilValidate.isNotEmpty() but rather https://stackoverflow.com/questions/17256855/checking-if-a-collection-is-null-or-empty-in-groovy#saves-btn-17256864
https://groovy-lang.org/semantics.html#_maps
I'll replace the few cases we have used UtilValidate.isNotEmpty() during migration

**Comment by PierreSmits** [comment]
Thanks @JacquesLeRoux ,

Your changes work for me.

**Pull request merged**
