### PR TITLE
Improved:  Remove ofbiz suffix from rest plugin, code cleanup (OFBIZ-12197)

### PR DESCRIPTION
**Pull request by mbrohl**
Refactoring and code cleanup for the rest-api plugin.
See https://issues.apache.org/jira/browse/OFBIZ-12197

### CODE REVIEW

**Comment by mbrohl** [comment]
@girishvasmatkar the bugs and security hotspots were introduced by the initial plugin implementation.
Can you please check them?

**Comment by mbrohl** [comment]
@girishvasmatkar what does the redoc.html file which currently causes SonarCloud to fail?
I do not find this file in the Swagger UI distribution files, everything else seems to match.

Do we need it or can it be removed?

**Comment by mbrohl** [comment]
> @girishvasmatkar the bugs and security hotspots were introduced by the initial plugin implementation.
> Can you please check them?

Ok, I've now fixed the SonarCloud errors. Please check the pull request if it can be committed so I can work from there, thanks.

**Comment by girishvasmatkar** [comment]
@mbrohl redoc.html is not part of Swagger UI. It is a separate UI similar to Swagger that also reads the OpenAPI spec YAML/JSON files and renders a nice presentable HTML
I should be able to take a look at the PR today. Thank you Micahel.

**Review by girishvasmatkar — COMMENTED** [review]
Hi, @mbrohl : It all looks good to me.

**Comment by mbrohl** [comment]
Thanks @girishvasmatkar !

**Pull request merged**
